SYSTEM_NAME="capcom"
SYSTEM_FULLNAME="Capcom Classics"
SYSTEM_MANUFACTURER="Capcom"
SYSTEM_RELEASE="1984"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/capcom"
SYSTEM_EXTENSION=".zip .7z"
SYSTEM_PLATFORM="arcade"
SYSTEM_THEME="fbneo"
SYSTEM_WIKI_PATH="arcade"
