SYSTEM_NAME="killerinstinct"
SYSTEM_FULLNAME="Killer Instinct Arcade"
SYSTEM_MANUFACTURER="Rare"
SYSTEM_RELEASE="1994"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/killerinstinct"
SYSTEM_EXTENSION=".chd .bin .zip"
SYSTEM_PLATFORM="arcade"
SYSTEM_THEME="killerinstinct"
SYSTEM_WIKI_PATH="killerinstinct"
