SYSTEM_NAME="mariohack"
SYSTEM_FULLNAME="Mario Hacks (SMW)"
SYSTEM_MANUFACTURER="Nintendo"
SYSTEM_RELEASE="1990"
SYSTEM_HARDWARE="console"
SYSTEM_PATH="/storage/roms/mariohack"
SYSTEM_EXTENSION=".sfc .smc .bs .st .zip .7z"
SYSTEM_PLATFORM="snes"
SYSTEM_THEME="snes"
SYSTEM_WIKI_PATH="snes"
