SYSTEM_NAME="markiii"
SYSTEM_FULLNAME="Sega Mark III"
SYSTEM_MANUFACTURER="Sega"
SYSTEM_RELEASE="1985"
SYSTEM_HARDWARE="console"
SYSTEM_PATH="/storage/roms/markiii"
SYSTEM_EXTENSION=".sms .sg .bin .rom .mv .zip .7z"
SYSTEM_PLATFORM="mastersystem"
SYSTEM_THEME="mastersystem"
SYSTEM_WIKI_PATH="mastersystem"
