LABEL NextOS
  LINUX /KERNEL
  FDTDIR /dtbs/
  ## FDT: don't forget the leading slash, remove all symbols after .dtb (including whitespace)
  # FDT /dtbs/your-custom-devicetree.dtb
  FDTOVERLAYS /overlays/mipi-panel.dtbo
  APPEND boot=${partition_boot} root=${partition_root} disk=${partition_storage} @EXTRA_CMDLINE@ uboot.hwid_adc=${hwid_adc}
